export default {
  styles: {
    root: {
      color: 'text',
      fontFamily: 'body',
      fontSize: 'body',
      fontWeight: 'body',
      lineHeight: 'body',
    },
    h1: {
      color: 'text',
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'heading',
      fontSize: 'h1',
    },
    h2: {
      color: 'text',
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'heading',
      fontSize: 'h2',
    },
    h3: {
      color: 'text',
      fontFamily: 'heading',
      lineHeight: 0,
      fontWeight: 'heading',
      fontSize: 'h3',
    },
    h4: {
      color: 'text',
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'heading',
      fontSize: 'h4',
    },
    h5: {
      color: 'text',
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'heading',
      fontSize: 'h5',
    },
    h6: {
      color: 'text',
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'heading',
      fontSize: 'h6',
    },
    p: {
      color: 'text',
      fontFamily: 'body',
      fontWeight: 'body',
      lineHeight: 'body',
    },
    a: {
      color: 'primary',
      textDecoration: 'none',
      '&:hover': {
        textDecoration: 'underline',
      },
    },
    blockquote: {
      borderLeftColor: 'muted',
      borderLeftStyle: 'solid',
      borderLeftWidth: 5,
      color: 'textSecondary',
      fontStyle: 'italic',
      fontFamily: 'body',
      m: 0,
      p: 2,
    },
    pre: {
      bg: 'muted',
      borderRadius: 8,
      color: 'primary',
      fontFamily: 'monospace',
      p: 2,
      textAlign: 'left',
      overflowX: 'auto',
    },
    code: {
      color: 'primary',
      fontFamily: 'monospace',
      fontSize: '0.8em',
    },
    table: {
      width: '100%',
      borderCollapse: 'separate',
      borderSpacing: 0,
    },
    th: {
      textAlign: 'left',
      borderBottomStyle: 'solid',
    },
    td: {
      textAlign: 'left',
      borderBottomStyle: 'solid',
    },
    img: {
      maxWidth: '100%',
    },
  },
}
